### ISSUE TITLE
Build error: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by jderr-mx** [ef4/cardstack-editor#2]
When trying to run `ember build` or `ember serve` I get the error 

```
TypeError: Cannot read property 'app' of undefined
    at CoreObject.module.exports._findApp (/home/john/git/dev/cardstack-editor/node_modules/ember-concurrency/index.js:26:15)
    at CoreObject.module.exports._includePolyfill (/home/john/git/dev/cardstack-editor/node_modules/ember-concurrency/index.js:20:24)
    at CoreObject.module.exports.included (/home/john/git/dev/cardstack-editor/node_modules/ember-concurrency/index.js:10:10)
    at CoreObject.included (/home/john/git/dev/cardstack-editor/node_modules/core-object/lib/assign-properties.js:32:18)
    at /home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/addon.js:241:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/addon.js:239:24)
    at CoreObject.extend.included (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/addon.js:367:10)
    at CoreObject.included (/home/john/git/dev/cardstack-editor/node_modules/core-object/lib/assign-properties.js:32:18)
    at EmberAddon.<anonymous> (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/broccoli/ember-app.js:435:15)
```

`ember test` Results in: 

```
Cannot read property 'app' of undefined
TypeError: Cannot read property 'app' of undefined
    at CoreObject.module.exports._findApp (/home/john/git/dev/cardstack-editor/node_modules/ember-concurrency/index.js:26:15)
    at CoreObject.module.exports._includePolyfill (/home/john/git/dev/cardstack-editor/node_modules/ember-concurrency/index.js:20:24)
    at CoreObject.module.exports.included (/home/john/git/dev/cardstack-editor/node_modules/ember-concurrency/index.js:10:10)
    at CoreObject.included (/home/john/git/dev/cardstack-editor/node_modules/core-object/lib/assign-properties.js:32:18)
    at /home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/addon.js:241:34
    at Array.map (native)
    at CoreObject.eachAddonInvoke (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/addon.js:239:24)
    at CoreObject.extend.included (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/addon.js:367:10)
    at CoreObject.included (/home/john/git/dev/cardstack-editor/node_modules/core-object/lib/assign-properties.js:32:18)
    at EmberAddon.<anonymous> (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/broccoli/ember-app.js:435:15)
    at Array.filter (native)
    at EmberAddon.EmberApp._notifyAddonIncluded (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/broccoli/ember-app.js:430:45)
    at EmberAddon.EmberApp [as appConstructor] (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/broccoli/ember-app.js:109:8)
    at new EmberAddon (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/broccoli/ember-addon.js:38:8)
    at module.exports (/home/john/git/dev/cardstack-editor/ember-cli-build.js:6:13)
    at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/builder.js:54:19)
    at CoreObject.module.exports.Task.extend.init (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/models/builder.js:89:10)
    at CoreObject.init (/home/john/git/dev/cardstack-editor/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/home/john/git/dev/cardstack-editor/node_modules/core-object/core-object.js:32:33)
    at CoreObject.<anonymous> (/home/john/git/dev/cardstack-editor/node_modules/ember-cli/lib/commands/test.js:142:30)
    at lib$rsvp$$internal$$tryCatch (/home/john/git/dev/cardstack-editor/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/john/git/dev/cardstack-editor/node_modules/rsvp/dist/rsvp.js:1048:17)
```

Node and ember versions are: 

```
ember-cli: 2.6.0-beta.2
node: 0.12.15
os: linux x64
```

I had the same issue trying to build on an OS X machine too.

Please let me know if there is more information I can provide.

**Comment by signal-intrusion** [comment]
+1

**Comment by ef4** [comment]
Please try as of c0566053359307c08375cf3bfbb9fc4c5cc9259b

I had an unpushed commit that was halfway through renaming the addon.

**Comment by signal-intrusion** [comment]
Tried the latest. Same error for me. I'm fairly certain that this bug is caused by a bug in ember-concurrency which was solved in `0.6.1` of that addon. See this PR: https://github.com/machty/ember-concurrency/pull/46. I submitted a PR which should take care of this. :)

**Comment by code0100fun** [comment]
I had to update `ember-cli-import-polyfill` to `0.2.0` to fix it for me.

**Comment by crestway** [comment]
Is there a patch. I'm still getting it?
